[package]
name = "tam_tam_bot"
version = "0.1.0"
authors = ["Anton Kuzmin <sassanid18gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"